---
name: Release Minor
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: cliffano/release-action@v2.0.0
        with:
          release_type: minor
          github_token: ${{ secrets.SHINEWORKS_GITHUB_TOKEN }}
          git_user_email: shinesworks@shinesolutions.com
          git_user_name: Shine Works
